name: Releases

on:
  push:
    tags:
      - v*


jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go version 1.16.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          go-version: 1.18.x

      - name: Build Artifacts
        if: "contains(github.ref, 'refs/tags/v')"
        run: |
          make build
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            ./bin/mqtt-bench-linux-amd64.bin
            ./bin/mqtt-bench-darwin-amd64.bin
